---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: sea-plane
  name: vault
data:
  default.hcl: |
    api_addr = "https://vault.sea-plane.svc.cluster.local"
    listener "tcp" {
      address = "0.0.0.0:8200"
      tls_disable = 1
    }
    storage "file" {
      path = "/vault/file"
    }

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: sea-plane
  name: vault
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: sea-plane
  name: vault
spec:
  serviceName: vault
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      volumes:
        - name: config
          configMap:
            name: vault
        - name: data
          persistentVolumeClaim:
            claimName: vault

      containers:
        - name: vault
          image: vault
          securityContext:
            capabilities:
              add: 
                - IPC_LOCK

          volumeMounts:
            - name: data
              mountPath: /vault/file
            - name: config
              mountPath: /vault/config

          ports:
            - name: vault
              containerPort: 8200

          command:
            - vault
            - server
            - -config
            - /vault/config/default.hcl

---
apiVersion: v1
kind: Service
metadata:
  namespace: sea-plane
  name: vault
spec:
  type: ClusterIP
  selector:
    app: vault
  ports:
    - name: vault
      targetPort: vault
      port: 8200
